[package]
name = "email-cron"
version = "0.1.0"
edition = "2021"

[dependencies]
imap = "2.4.1"
native-tls = {version = "0.2.13", features = ["vendored"]}
chrono = "0.4.39"
unic-emoji-char = "0.9.0"
unicode-segmentation = "1.12.0"
regex = "1.11.1"
dotenv = "0.15.0"
